name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    env:
      JAVA_VERSION: "22.2.r17-grl"

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          no-cache: false
          build-args: JAVA_VERSION="${{ env.JAVA_VERSION }}"
          tags: softinstigate/graalvm:latest,softinstigate/graalvm:${{ env.JAVA_VERSION }}
