name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push multi-arch Docker images
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64,
            linux/arm64
          push: true
          pull: true
          no-cache: false
          tags: |
            softinstigate/graalvm:latest,
            softinstigate/graalvm:${{ github.ref_name }}
