name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set the JAVA_VERSION
        id: vars
        run: |
          echo "::set-output name=JAVA_VERSION::$(echo ${GITHUB_REF:10})"
          echo "JAVA_VERSION=${{steps.vars.outputs.JAVA_VERSION}}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: false
          build-args: JAVA_VERSION="${{ steps.vars.outputs.JAVA_VERSION }}"
          tags: softinstigate/graalvm:latest,softinstigate/graalvm:${{ steps.vars.outputs.JAVA_VERSION }}
